### ISSUE TITLE
Pass appropriate default selections when creating new content

### ISSUE THREAD

**Issue by neagle** [usgo/gocongress#104]
Most (all?) of our "New" buttons for Creating new content or creating new plans don't pre-select the correct item in the select in the following page.

Example:

1. Make sure you have multiple content categories created.
2. Go to one of the content categories that is not listed first in the select under "new content".
3. Click the "New Content" button.
4. Observe that the first item in the select is active, not the item for the content category you were just viewing.

Sometimes it makes sense not to pre-populate a selection, but when a button is already within a parent context, it should pass that to the next page. (This tripped me up a few times when creating plans.)

**Comment by neagle** [comment]
@compostbrain This may be one that you could handle, given your rails experience. I investigated it a bit, but my knowledge of how params/routing works in Rails, along with the `new_*_path` helper left me temporarily stymied.

**Comment by compostbrain** [comment]
@neagle Would adding a prompt to the select box such as 'Select Category' be sufficient?  This would be the simplest solution.  Otherwise, I think I would need to use nested routing in order to access the parent context you refer to.

**Comment by neagle** [comment]
Adding "Select Category" as an empty selection would make there be _no_ default, rather than possibly the wrong default, which would be an improvement. But not as good as populating it correctly! I agree that either adding another slug to the route or adding a query param is likely necessary to make this possible.
