### ISSUE TITLE
Fix gocongress.org → www.gocongress.org redirect

### ISSUE THREAD

**Issue by neagle** [usgo/gocongress#152]
Right now, gocongress.org is not properly redirecting to www.gocongress.org. I suspect it was broken when certificates were set up for the site, as there's an on-going certificate error on Heroku:

![image](https://user-images.githubusercontent.com/176993/46675991-a0103e80-cbad-11e8-807e-4dcfcb9b8bb3.png)

**Comment by vash3g** [comment]
Update: working to move DNS from Linode to AWS Route53 to allow for Alias records for the heroku style of DNS.

**Comment by vash3g** [comment]
Moved Domain/DNS to AWS Route 53. Redirect working for http, https not supported for redirect.
