### ISSUE TITLE
Make site usable on mobile browsers

### ISSUE THREAD

**Issue by neagle** [usgo/gocongress#163]
Using style utilities added for the 2018 site (https://github.com/neagle/gocongress/blob/master/app/assets/stylesheets/mixins/_breakpoint.scss), update design with breakpoints to make the site usable on narrow screens. One of the core challenges will be the tables used for registration and other admin sections. This looks like a relatively approachable task, but it involves quite a bit of re-work. Consider this one of the major tasks for 2020! :)

You can check out the 2018 site's styles for reference: https://github.com/neagle/gocongress/blob/master/app/assets/stylesheets/2018/main.css.scss

History: the 2018 site was completely responsive, but it used a lot of custom styles and templates, doesn't apply to the design for the other years. It _might_ be easier to fold this task into a more general redesign of the site.

**Comment by joelcahalan** [comment]
I would think something like [TailwindCSS](https://tailwindcss.com/) might be good for this. Thoughts?

**Comment by hajinlee** [comment]
Seems like the site is looking better on mobile now! Is this still an issue?

**Comment by neagle** [comment]
This is somewhat resolved -- most of the site works well on mobile, now, but *forms* do not. That said, I think we can save that as part of the next redesign.
