### ISSUE TITLE
Try to keep GoCongress site emails out of people's SPAM folders

### ISSUE THREAD

**Issue by neagle** [usgo/gocongress#173]
We got a report from an attendee that their welcome email got directed to their spam folder. Obviously, preventing this from happening is not entirely within our control, but there are a number of best practices out there that we could make sure we're taking to do our best to show that our emails are legitimate. Go forth, run through this list of best practices, and see how many we can easily implement.

**Comment by vash3g** [comment]
What is the service used to send email? We may need to include this in enhanced spam control. @gocongress.org addresses should be fine unless theyre going through a relay.

**Comment by neagle** [comment]
We use a very basic Ruby on Rails feature called [Action Mailer](https://guides.rubyonrails.org/action_mailer_basics.html). I don't know much about it as I haven't messed with the mailer here before, and this is the only RoR project I've ever worked on. There may be various configuration options we could change to make emails sent through it less likely to be flagged as SPAM, or, as maybe you were suggesting, we could consider using a service like SendGrid, or even just Gmail's service through one of the Congress addresses.

**Comment by vash3g** [comment]
I setup SES at one point for this but it was cancelled when someone used it and it went off on a million people and no one responded. I can attempt to set that up again as it was a no-reply@usgo.org. We could do a similar with @gocongress.org as we own the domain. Gmail has sending limits which we may hit for the congress site. 

What is the address currently sending emails out through action mailer?

**Comment by neagle** [comment]
Looks like we're going to be dealing with at least part of this request through #207.

There are a few action items listed under "authentication" in this guide that we'll still want to take separately: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/tips-and-best-practices.html

**Comment by neagle** [comment]
We've elected to stick with Gmail's SMTP server for now, rather than start using a transactional email service. Until we need to send more than 500 emails a day, Gmail is a very practical solution for this site, and there's nothing that doesn't start around $15/month that can replace it.

**Comment by etower366i2** [comment]
Sticking with gmail makes sense and I have no problem with it, but we do
actually have the need to send over 500 emails per day.

I sent emails to all registrants multiple times last year, and at least
once ended up getting someone else to help with half of them so that we
could get them all out the same day.  Other times, I had to split the
emailing over two days.


Dr. Lisa Scott
Author, Researcher, Historian

**Comment by neagle** [comment]
@etower366i2 Ah, that's a good point, but a separate issue. This is only related to emails sent programatically by the website. It certainly makes sense that you'd need the ability to email everyone attending for announcements, but right now the website doesn't do that, it just has a place where you can grab all the emails of attendees so that you can do it youself.

If we wanted the website to be able to send announcements, that could certainly be a case for upgrading to an actual email service.
