### ISSUE TITLE
KGS Username validation

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#189]
Ability to validate the KGS username on registration. Can use `http://gokgs.com/gameArchives.jsp?user=[user]` to see if a page exists.

**Comment by EarthSchlange** [comment]
KGS does not actually return a status error here i.e., "404 Not Found." KGS returns a page with an error message. In the case of the example below, that is: `Sorry, there are no games in the archives for user kgsuser. Please try another search.` If we are looking for to see if a user is valid by parsing the HTML, we could run into issues down the road if KGS every changes their error messages. Though, that may not necessarily be a likely issue. 

![Screenshot from 2021-06-16 22-05-25](https://user-images.githubusercontent.com/5054653/122334726-04533680-ceef-11eb-9dde-5cadfb658f5d.png)

**Comment by EarthSchlange** [comment]
Closing. This is resolved in #200.
