### ISSUE TITLE
Ability for users to sign up for tournaments during registration

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#190]
Allow users to sign up for tournaments during registration. This will allow TDs to download an opengotha file to manage the tournament. This is mostly good for e-Go Congress. Will have to look for future use at in person congresses.

**Comment by neagle** [comment]
Looks like this feature once existed! 51f4744eb6ec5c790596a89f9e51cac4d0a3d2f4

I'm starting work on adding the feature back now. Just out of curiosity, @jaredbeck, do you remember why this feature was removed back in 2012?

**Comment by jaredbeck** [comment]
> Just out of curiosity, @jaredbeck, do you remember why this feature was removed back in 2012?

Man, I can't remember what I ate for breakfast let alone eight years ago 😆 Maybe the director that year wanted to simplify the form? Get to the payment more quickly?

**Comment by neagle** [comment]
@etower366i2 That's really useful information. I can imagine the confusion, but I agree with you that it's a useful feature, and I think we might be able to come up with some ways to manage it to preserve the flexibility of being able to let people show up for the more casual tournaments during the Congress while getting some benefit from having participation medidated through the site.

**Comment by neagle** [comment]
Closed by #208.
