### ISSUE TITLE
Switch asset_sync to use S3 bucket in AGA account

### ISSUE THREAD

**Issue by neagle** [usgo/gocongress#199]
...also investigate how much trouble it would be to access it through Cloudfront. Having a CDN in front of it should yield performance benefits for users, especially once outside the eastern US.

@vash3g recommends chatting with @EarthSchlange, who set up the CDN for the webpage assets.

**Comment by EarthSchlange** [comment]
Having Cloudfront sit in front of an AWS S3 bucket should not be a really difficult task. @neagle  What is your plan to build and deploy web assets to this new AWS S3 Bucket?

**Comment by EarthSchlange** [comment]
Also, possibly duplicate of #51.
