### ISSUE TITLE
Go Congress Deployment Goes Off Screen

### ISSUE THREAD

**Issue by EarthSchlange** [usgo/gocongress#202]
## Summary
On mobile, https://gocongress.herokuapp.com/ site is allowed scroll to go off screen to the left.

## Screenshot(s)
![Screenshot_20210514-090837](https://user-images.githubusercontent.com/5054653/118298597-82599300-b494-11eb-88be-87b96227c0e1.png)

**Comment by neagle** [comment]
The mobile styles definitely need some attention. Thanks for pointing this out. :)
