### ISSUE TITLE
The USGO Congress Signin Page Displays Forgot Password Above Signin

### ISSUE THREAD

**Issue by EarthSchlange** [usgo/gocongress#209]
## Summary
On most sites when viewing on mobile the "Sign In" form is above the "forgot password" section. However, on the Go Congress [Sign In](https://gocongress-dev.herokuapp.com/2021/sign_ups/sign_in) the "Sign In" form is below the "forgot password" section.

## Expected Behaviour 
The Sign In form be above "forgot password."

## Screenshots
![Screenshot from 2021-06-03 12-59-18](https://user-images.githubusercontent.com/5054653/120705167-55354a80-c46c-11eb-8623-f6bfb3257f3b.png)

**Comment by neagle** [comment]
Closed by 421ac683d169d832d6e1254c8d13b0e9140ec297. 

![2021-06-16 at 3 29 PM](https://user-images.githubusercontent.com/176993/122281017-cdadf980-ceb7-11eb-867e-81a30b4655b2.png)

Thanks for pointing this out, @EarthSchlange!
