### ISSUE TITLE
Ability to disable phone numbers and text messages

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#212]
## Is your feature request related to a problem?
By default the registration requires: phone number, receive text messages, emergency contact name, emergency contact phone

## Describe the feature you'd like to see on the Go Congress Site.
Online congresses need these less than in person events. These should be able to be either not required or option to be turned off. It is more difficult when a larger portion of attendees are not US based.

**Comment by jaredbeck** [comment]
I can't think of any reason an online Congress would need emergency contact info, hiding those fields makes sense to me.

For the phone number field, are there concerns that the Registrar, Youth Coordinator, or TD might have? I'm thinking the Registrar might want to still have phone numbers to resolve billing issues. Or, a TD might want phone numbers in case they have attendance problems in the Open section, or like, after the Congress, if they need to send out a prize? Just brainstorming ..

**Comment by vash3g** [comment]
We're also utilizing the baduk.club tournament software to manage rounds. This will help get in contact with players. There were issues last year with players not showing up for rounds and it was primarily handled through email or usernames. The new software will help connect with people. We dont have a youth coordinator this year and im not sure what TD we may have for this. We have fewer events overall. If we can verify emails that will circumvent some of the needs of phone numbers. Even if we have/import their phone number it may not be necessarily Required for the event. That would be tough to also make overseas calls for some people.

**Comment by etower366i2** [comment]
I think the other main thing, to answer your brainstorm (which I also did
Thursday at the meeting) is that we're not charging a registration fee, so
we don't need to worry about billing.

Best,
Lisa

Lisa Scott
Chairperson of the Board of Directors
Congress Coordinator
Coordinator for Diversity and Inclusion
American Go Association

**Comment by jaredbeck** [comment]
Cool, sounds like yall thought this through. Makes sense to me.
