### ISSUE TITLE
Create way to add outside links

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#214]
## Is your feature request related to a problem?
Add ability to add external link for other site.

## Describe the feature you'd like to see on Go Congress.
We have a go congress store and it would be good to be able to easily link it somewhere. It wont always have the same things but someone is working on a central way to store product and be able to ship it.

## Notes
https://store.gocongress.org

**Comment by jaredbeck** [comment]
Where do you want to put the link? If you want it on the home page, you can do that under Content -> Editable Text -> Welcome.
