### ISSUE TITLE
No Documentation Provided on How to Register a User for Local Development

### ISSUE THREAD

**Issue by EarthSchlange** [usgo/gocongress#221]
## Is your feature request related to a problem?
When loading the GoCongress Website, there seems to be no documentation on how GoCongress users are created for local development. It is also not clear how one should register a new user for local development. For example, one may expect to register here: http://localhost:3000/2021/sign_ups/sign_up; however, that page provides no form for development purpose.

## Describe the feature you'd like to see on the Go Congress Website.
Documentation on how to create a registered user for local development on the GoCongress website.

## Screenshots
![Screenshot from 2021-06-16 22-44-45](https://user-images.githubusercontent.com/5054653/122338779-01f3db00-cef5-11eb-9933-2610e81a67d6.png)

![Screenshot from 2021-06-16 22-52-16](https://user-images.githubusercontent.com/5054653/122339160-93fbe380-cef5-11eb-9741-f57528fe2824.png)

**Comment by neagle** [comment]
This is definitely a gap in the documentation. I'll try to address it ASAP. Thanks, @EarthSchlange!
