### ISSUE TITLE
"Are you playing in US Open" should be removed

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#225]
## Is your feature request related to a problem?
In the default registration form there is a question for "Are you playing in the US Open". This asks for yes/no option.

## Describe the feature you'd like to see on the Go Congress Website.
If tournament registration is moved to individual tournaments this can cause confusion for some players. This is essentially listed twice if the US Open is allowed to be individually registered for. We should remove the option and force registration through individual tournaments when they are listed on the website.

## Notes
Add any other information or screenshots about the feature request here.

**Comment by neagle** [comment]
Yeah, this had been on my mind. I think we will go ahead and commit to removing it -- that means I'll also need to remove the U.S. Open-specific functionality in the admin area. But we're basically transitioning all of that to be generalized to all tournaments, so it's mostly a transfer. I'll be working on all that this weekend.
