### ISSUE TITLE
User Must Have a Confirmed Email 

### ISSUE THREAD

**Issue by EarthSchlange** [usgo/gocongress#230]
## Summary of the Bug
If the user created in the instructions does not have a confirmed email, one cannot Sign In.

## Steps to Reproduce the Behaviour
1. Follow the steps for creating a user in GoCongress instructions.
2. Attempt to Sign In on http://localhost:3000/2021/sign_ups/sign_in

## The Expected Behaviour
One should be able to Sign In to the 2021 year without verification for development.

## Screenshots
![Screenshot from 2021-06-19 14-17-28](https://user-images.githubusercontent.com/5054653/122655721-7bfcad80-d109-11eb-8f40-7a4c19168201.png)

**Comment by EarthSchlange** [comment]
When testing a second time, this issue seems resolved. Cannot reproduce.

**Comment by neagle** [comment]
Yeah, there must have been something going on with exactly when you created your user -- this line in the user account creation script makes sure that the new account is already treated as confirmed: https://github.com/usgo/gocongress/pull/229/files#diff-b6358c5d68b103b660c64877e5e333b07ae4221ddf5a8ebced0b9eb0da523902R8
