### ISSUE TITLE
Ability to remove/delete user accounts

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#244]
## Is your feature request related to a problem?
When emailing users to make sure they fully register, signed up but no attendees, their email bounces with bad email.

## Describe the feature you'd like to see on the Go Congress Website.
I would like the ability to delete these account which will not become attendees. Generally a small number of accounts.

## Notes
Add any other information or screenshots about the feature request here.

**Comment by neagle** [comment]
This definitely makes sense. Let's add the ability to de-activate a user, ensuring that their email doesn't show up in the list of user emails, and that they don't show up in any user lists.

**Comment by vash3g** [comment]
Both sound good. Hiding them is the easy first option because of the verification layer (awesome!). Is there potentially a timeout period for the verification of [if account not verified after X days, do not show/remove account]?

**Comment by neagle** [comment]
At this time, I don't think we need to add the ability to delete users. I've added a filter to show only confirmed users wherever they're listed in the UI. Closed by #245.
