### ISSUE TITLE
All tournament reports have listed "X players are registered for the US Open"

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#250]
## Summary of the Bug
When looking at a tournament report pages all of the lines below the 'Export' button say "There are X attendees registered to play in the U.S. Open." regardless of what tournament is selected.

## Steps to Reproduce the Behaviour
1. Go to a tourament report
2. Click on 'DDK Tournament'
3. Scroll down to just past the "Export" button

## The Expected Behaviour
This should list the actual tournament name

## Screenshots
![image](https://user-images.githubusercontent.com/994470/123701100-62591580-d82f-11eb-9896-37e498132ea5.png)

**Comment by neagle** [comment]
I swear I saw this and fixed it when making adjustments to the original PR. Must've let it slip through somehow. Thanks for reporting!
