### ISSUE TITLE
Remind attendees to tick the tournament checkmark if they provide a username

### ISSUE THREAD

**Issue by 0lionelzhang0** [usgo/gocongress#251]
## Is your feature request related to a problem?
There are several instances (e.g. 4 cases for pair go) where an attendee fills in their server username but forgets to tick the tournament checkbox. These players end up not included in the tournament xml exports. 

## Describe the feature you'd like to see on the Go Congress Website.
Just like how attendees are required to enter a server username when they tick a tournament checkbox, they should also be reminded or required to tick the checkbox if a username is provided for that tournament.

**Comment by vash3g** [comment]
A new EJ post went out about this today. We will email players directly to remind them as well!
https://www.usgo.org/news/2021/06/registration-for-e-go-congress-tournaments/

**Comment by neagle** [comment]
https://user-images.githubusercontent.com/176993/124049915-75164a80-d9e7-11eb-969a-be6582bdd998.mov

Now, when a user types their username in an input, the tournament will automatically be selected.
