### ISSUE TITLE
Registration confusion when adding attendee post signup

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#256]
## Summary of the Bug
When signing up there is a search box for AGA members and a button that states "This attendee is not an AGA member". This causes some players to be confused even when they are AGA members.

## Steps to Reproduce the Behaviour
**i.e.,**
1. Sign up on the go congress website
2. Click on 'Add Attendee'
3. Do not search, (or pass go,) and wonder why you dont see your AGA account.
4. Attendee emails director/registrar for help registering for event

## The Expected Behaviour
Player searches in text box. Suggestion to change secondary button to "Click here is you are not an AGA member". Suggestion to also change textbox text from "Go Seigen" to "Enter AGA ID or Name". If we keep "Go Seigen" then we should also display "Go Seigen or [Fake AGA ID]".

## Screenshots
![image](https://user-images.githubusercontent.com/994470/124021409-85afcc00-d9b9-11eb-9009-bbd6c54b66c4.png)

## Notes
From an actual player email.

**Comment by neagle** [comment]
Yeah, this is some important UI feedback. Looks like it's time to take a second pass at the design of this component.

**Comment by neagle** [comment]
Reworked the UI to look like this, taking a number of suggestions from your issue:

![2021-06-30 at 8 51 PM](https://user-images.githubusercontent.com/176993/124048796-1cde4900-d9e5-11eb-85eb-879ddae18f7f.png)

Let me know how this goes -- definitely want to keep confusion to a minimum.

Closed by ba9df56.
