### ISSUE TITLE
add option to grey out plan but still display to users

### ISSUE THREAD

**Issue by thoel** [usgo/gocongress#26]
There is currently a "disable" option for every plan to turn it off and hide it from view.  It would also be useful to grey out a plan and make it not selectable, but still display it to users.  In particular this could be very useful in the Late Registration section to grey out options that are not currently valid.  For example, in June the late fee is $50, and the greyed out options show it was free in May, and will go up to $100 in July.

**Comment by rcristal** [comment]
Done.  Initial version of this option is now available.  You might need to use the following:

```$ rake db:migrate``` (to modify your local database)
```$ bundle exec rake db:test:prepare``` (to prepare the modified database for testing)

**Comment by thoel** [comment]
Rex,

This new feature works great!  Thank you.  If you want to see what we're 
doing, my system is:

     184.97.137.91:3000

Any suggestions are welcome.

Tim

**Comment by thoel** [comment]
This new feature works great!  Thanks.

**Comment by rcristal** [comment]
Updated.
