### ISSUE TITLE
Add server username to tournament report display

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#264]
## Is your feature request related to a problem?
Tournament report does not display go server username for TDs for online tournaments

## Describe the feature you'd like to see on the Go Congress Website.
Add a list of the go server username to the general report to help TDs match players and handles

## Notes
Current display looks like:
![image](https://user-images.githubusercontent.com/994470/124366597-f4da2a00-dc1e-11eb-8804-7826e5ab595a.png)

**Comment by neagle** [comment]
Does this need to go into the XML export, too? Any chance you know what the field name needs to be?

**Comment by vash3g** [comment]
I dont know about the XML export at this time. I would bet the copy/paste of the table could work with excel/g-docs or equivalent. I know Luc added a field in OpenGotha and have not looked it up yet.

**Comment by neagle** [comment]
Okay -- I just downloaded OpenGotha and it doesn't look like there's actually a new release, yet. Maybe I'm missing something. But for the moment I've added it to the table, which should be useful for exactly the reason you mention, and hopefully we can add support for the player export at some future point.
