### ISSUE TITLE
add "set all" and "clear" to per-day plans

### ISSUE THREAD

**Issue by thoel** [usgo/gocongress#27]
Allowing users to select individual days in per-day plans is a very useful feature for attendees who arrive late or leave early.  However, it is not very convenient for most users who stay for the full week.  Within the check box cell it would be nice to add commands for "set all" and "clear" to make the job easier.

**Comment by rcristal** [comment]
Initial version of a set all and clear option for daily plans on the registration form is now available.

**Comment by thoel** [comment]
New version with "Set All" and "Clear" buttons works well.
