### ISSUE TITLE
List of emails for signed up Activities

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#271]
## Is your feature request related to a problem?
When you look at an activitiy there is not an easy way to get all of the peoples email addresses.

## Describe the feature you'd like to see on the Go Congress Website.
Add a box similar to the tournament reports for people in charge of activities to easily copy from.

## Notes
Add any other information or screenshots about the feature request here.

**Comment by neagle** [comment]
Definitely makes sense as a need! Added.
