### ISSUE TITLE
Add number of countries on who's coming page

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#274]
## Is your feature request related to a problem?
Site currently displays basic stats for number of players in the entire event.

## Describe the feature you'd like to see on the Go Congress Website.
Display number of countries of players participating to give idea how widespread we gather players from. For example e-Go Congress has 28 countries with the last week of the event available for registration.

## Notes
28 Countries!?!?!?! So much!

**Comment by neagle** [comment]
This is definitely a nice idea -- having people attending from so many places around the globe is a great thing to highlight.
