### ISSUE TITLE
Provide a tournament export for "Go Server Username Export"

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#277]
## Is your feature request related to a problem?
For an online congress TDs should be able to display the player's usernames rather than real names.

## Describe the feature you'd like to see on the Go Congress Website.
This export would replace "First Name" with "[collected site signup username]" and there should be no "Last Name" field entered. 
The rest of the information for the XML file could be published. 
OpenGotha does not display AGAID for pairings nor standings. 

## Notes
This is partially for player privacy for people who wish their real name to be anonymous.

**Comment by neagle** [comment]
I've added a new button to export a version of a tournament's players list with only go server usernames. 43f0818c360cccb67e54645ee4d2716c00958cbf

![2021-07-17 at 8 02 AM](https://user-images.githubusercontent.com/176993/126036253-6498763a-9a3c-4d6e-9a37-e676ea4ac92a.png)
