### ISSUE TITLE
Improve pop-up linked to "No AGA ID" on New Attendee form

### ISSUE THREAD

**Issue by thoel** [usgo/gocongress#29]
This pop-up should encourage people to join the AGA *before* they show up at the Congress, to simplify the check-in process.  Perhaps something like:

Each AGA member is assigned an identification number.  Only AGA members may participate in AGA tournaments.

If you are not currently a member, please visit the AGA website and join before coming to the Congress.

**Comment by rcristal** [comment]
Done.

**Comment by thoel** [comment]
Looks good.  Thanks.
