### ISSUE TITLE
validate email address on user account creation

### ISSUE THREAD

**Issue by thoel** [usgo/gocongress#34]
For 2016:  currently a user can create a new account with an incorrect email address and we have no way of contacting them.  The system should accept a new email address (no password), send an email with a random password, and then have the user log in.  Also the system should force the user to enter a user name and phone number for the account, and not just rely on attendee info.

**Comment by jaredbeck** [comment]
Rex, you'll probably want to use [`Devise::Models::Confirmable `][1] for this.

[1]: http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Confirmable

**Comment by rcristal** [comment]
Convenient.  Thanks!

**Comment by jaredbeck** [comment]
Closed by https://github.com/usgo/gocongress/pull/207
