### ISSUE TITLE
Allow Uncancel by normal user

### ISSUE THREAD

**Issue by thoel** [usgo/gocongress#42]
This year a normal user was allowed to Cancel an attendee registration, but then was not allowed to Uncancel that attendee.  This limitation caused confusion and other problems.  This was done in case the attendee had requested a limited resource, such as room type, and Uncancel might over-subscribe the resource.  A better way would be to make Uncancel go through the standard error check, and only allow it to succeed after any over-subscription problems are fixed.

**Comment by rcristal** [comment]
Done.  If a user cancels an attendee, the plan selections of that attendee will be removed.  Attempting to restore the attendee will show the registration form.  After the form is submitted, the attendee will be restored.
