### ISSUE TITLE
For names, allow Given, Alternate, and Family

### ISSUE THREAD

**Issue by thoel** [usgo/gocongress#44]
When inputting the Attendee's name, provide three fields for Given, (Alternate), and Family names.  Many Asian players have both an Asian given name and an Americanized Alternate name.  When registering for activities, they will sometimes use their given name and at other times use their alternate name, which can be very confusing to the Congress organizers.  Also, some of these players might like to have both names appear on their badges.

**Comment by jaredbeck** [comment]
Interesting. Would it be appropriate to call an alternate name like this a "nickname"?

**Comment by rcristal** [comment]
Done.  If requested, we can change how we refer to alternate names.
