### ISSUE TITLE
Do not use Asset Sync

### ISSUE THREAD

**Issue by rcristal** [usgo/gocongress#51]
Heroku recommends using a CDN instead.  See https://devcenter.heroku.com/articles/please-do-not-use-asset-sync for more information.

**Comment by neagle** [comment]
I was just looking into this issue, too. Basically, Heroku doesn't consider S3 a good solution for serving static assets for a number of reasons. I basically agree, but I need to see how expensive it'll be to switch.

**Comment by vash3g** [comment]
@EarthSchlange has setup a CDN for some EJ content. Should there be similar setup for the gocongress?

**Comment by EarthSchlange** [comment]
We could do a similar setup. The heroku documentation basically agrees with this: 

> Using a Content Delivery Network (CDN) optimises the delivery of static assets on your site. This allows us to offload all requests for these static assets off of your web dynos, which in turn will free those dynos to handle more requests for dynamic content.

https://devcenter.heroku.com/articles/using-amazon-cloudfront-cdn
https://devcenter.heroku.com/articles/using-amazon-cloudfront-cdn#amazon-cloudfront

We would just be making a modification to production values and creating a Cloudfront distribution if everything goes smoothly.
