### ISSUE TITLE
Add state to "who's coming" page

### ISSUE THREAD

**Issue by amj** [usgo/gocongress#58]
Someone requested if it would be possible to add the state information to the "who's coming" page to help with carpooling, etc.

a) what do you think?
b) is it feasible?

**Comment by jaredbeck** [comment]
I don't think we collect addresses at all, just country. (Rex, am I remembering correctly?) It makes the registration form simpler, but I think this has been a problem in the past, when staff tries to mail things to attendees later.

Re: the "who's coming" page, there is a concern for anonymity. The way it was told to me, the people who request anonymity have real concerns about anyone finding out they attend. So, I guess it becomes a question of statistics. How likely is it, that by showing the state, we break someone's anonymity? More likely with the midwestern states, certainly.

**Comment by rcristal** [comment]
We can collect state data on the registration form and show the data of attendees who are not anonymous.

**Comment by neagle** [comment]
State information is now shown on the "Who is coming?" page.
