### ISSUE TITLE
Add Code of Conduct Agreement to Registration Page

### ISSUE THREAD

**Issue by etower366i2** [usgo/gocongress#78]
Users should have to check that they have read and agree to the Code of Conduct before they can complete registration.  Please let me know what further information is needed to make this happen as simply as possible.

The Code of Conduct should be approved later in the fall; in the meantime, we can use filler text.

**Comment by rcristal** [comment]
Was the Code of Conduct approved?

**Comment by etower366i2** [comment]
Good question.

It was, but we need to send it out to the chapters for more approval, so we
probably can't add it to the website yet.

Thanks for checking!

Lisa

**Comment by neagle** [comment]
The Code of Conduct is now part of the registration.
