### ISSUE TITLE
Use strong parameters

### ISSUE THREAD

**Issue by rcristal** [usgo/gocongress#86]
The protected attributes plugin is not compatible with Rails 5.0.

**Comment by compostbrain** [comment]
Hello Rex, I would like to start contributing to this project.  Nate and I are working together and he advised me to talk to you about where might be the best to plug in.  I poked around a little and looks like you have a branch for upgrading to rails 5.  Are there any issues that I could take a look at while that work is being done? Anything else I should be aware of? I have some Rails experience and would love to help out.

**Comment by rcristal** [comment]
Hi, Joel.  Thank you for your interest in helping out!  I will review the issues soon and provide some suggestions.

**Comment by rcristal** [comment]
There are several issues that might interest you.  Please take a look at #58 and #76, and let me know what you think.  You may also want to check with Nate and the organizers regarding #90.  During registration, I think it is ideal that you primarily work on reports with the organizers, but you can also work on other parts of the application.

The Rails upgrade process is almost complete.  I also plan on upgrading the integration with Authorize.Net.  According to the Authorize.Net upgrade guide, there is currently no end of life timeline for SIM.  We should be able to use SIM during registration.  I will contact Authorize.Net about this.

**Comment by compostbrain** [comment]
I will take a look at them. Thanks!

**Comment by compostbrain** [comment]
Rex,

I just updated by fork from upstream and I see you have updated rails to
version 5.0.6 and also ruby to 2.4.4.  Congrats on making the jump!

I am using rbenv to manage my ruby versions locally and for some reason
ruby 2.4.4 is not an available version.  I do have 2.5 installed locally.
Can we move to 2.5 or would that cause problems?

Thanks!

Regards,
Joel Cahalan

<https://github.com/compostbrain>

**Comment by compostbrain** [comment]
Rex,

Please disregard my prior email.  I realized I needed to update ruby-build
and now I have been able to install 2.4.4.


Regards,
Joel Cahalan

<https://github.com/compostbrain>

**Comment by rcristal** [comment]
Thank you, Joel!

**Comment by rcristal** [comment]
Done.
