### ISSUE TITLE
Guardian Name field does not work

### ISSUE THREAD

**Issue by rcristal** [usgo/gocongress#9]
Attempting to submit a guardian name results in the following message:

Please fix this 1 thing about your registration
Guardian can't be blank

**Comment by thoel** [comment]
I agree this is unnecessarily confusing and should be changed.  This should just be a text field with a non-blank requirement.  As Matthew says, the Liability Release Form is the legally binding document and that must be verified later by hand.

**Comment by rcristal** [comment]
Done.  Any remaining deprecations should eventually be removed.

**Comment by thoel** [comment]
Looks good.

**Comment by jaredbeck** [comment]
@rcristal can this issue be closed?

**Comment by rcristal** [comment]
The current plan is to use a drop-down selection box for the 2016 site.

**Comment by neagle** [comment]
Looks like this ended as a text field. Future Congress planners can reexamine the question of how they'd like the site to help structure guardianship responsibilities as part of sign up, but I'm closing this issue for now!
