### ISSUE TITLE
Get cert to enable https

### ISSUE THREAD

**Issue by neagle** [usgo/gocongress#95]
Received a request from AGA member Frank Brown to get https enabled for the Congress site, and I agree that it'd be a good idea.

**Comment by compostbrain** [comment]
i'd be willing to work on this if needed.  There are [heroku docs](https://devcenter.heroku.com/articles/ssl) and I think we could get a certificate with [Lets Encrypt](https://letsencrypt.org/getting-started/)

**Comment by rcristal** [comment]
Related to #72.

**Comment by compostbrain** [comment]
Can this be closed now?
